-- M-PG-TAB-01, 02, 03, 06, 07, 08, 10, 11, 12, 13, 14, 15, 16, 17, 18
-- plus the sequence backing TAB-11 and the base tables the index and view
-- fixtures read. Every row here runs on PostgreSQL 10 and later.

-- TAB-01: one column per common built-in type.
CREATE TABLE mx.t_tab_01 (
  c_int        integer,
  c_bigint     bigint,
  c_numeric    numeric(12,4),
  c_text       text,
  c_varchar    varchar(40),
  c_bool       boolean,
  c_date       date,
  c_timestamptz timestamptz,
  c_interval   interval,
  c_jsonb      jsonb,
  c_bytea      bytea,
  c_uuid       uuid,
  c_int_array  integer[],
  c_text_array text[]
);
INSERT INTO mx.t_tab_01
SELECT g,
       g * 1000000000::bigint,
       (g * 1.2345)::numeric(12,4),
       'text-' || g,
       'varchar-' || g,
       (g % 2 = 0),
       DATE '2020-01-01' + g,
       TIMESTAMPTZ '2020-01-01 00:00:00+00' + (g || ' hours')::interval,
       (g || ' days 3 hours')::interval,
       jsonb_build_object('n', g, 'tags', jsonb_build_array('a', 'b', g)),
       decode(lpad(to_hex(g), 8, '0'), 'hex'),
       ('00000000-0000-4000-8000-' || lpad(to_hex(g), 12, '0'))::uuid,
       ARRAY[g, g + 1, g + 2],
       ARRAY['x' || g, 'y' || g]
FROM generate_series(1, 25) g;

-- TAB-02: UNLOGGED table.
CREATE UNLOGGED TABLE mx.t_tab_02 (id integer PRIMARY KEY, payload text);
INSERT INTO mx.t_tab_02 SELECT g, 'unlogged-' || g FROM generate_series(1, 10) g;

-- TAB-03: relation storage parameters.
CREATE TABLE mx.t_tab_03 (id integer, payload text) WITH (fillfactor = 70);
INSERT INTO mx.t_tab_03 SELECT g, 'fill-' || g FROM generate_series(1, 5) g;

-- TAB-06: classic inheritance, rows in parent and child. The child must not
-- declare a local NOT NULL on an inherited column: that is a refused shape.
CREATE TABLE mx.t_tab_06 (id integer, msg text);
CREATE TABLE mx.t_tab_06_child () INHERITS (mx.t_tab_06);
INSERT INTO mx.t_tab_06 SELECT g, 'parent-' || g FROM generate_series(1, 10) g;
INSERT INTO mx.t_tab_06_child SELECT g, 'child-' || g FROM generate_series(1, 7) g;

-- TAB-07: dropped columns leave permanent holes in pg_attribute.attnum.
CREATE TABLE mx.t_tab_07 (id integer, keep_a text, drop_a text, drop_b integer, keep_b text);
INSERT INTO mx.t_tab_07 SELECT g, 'a' || g, 'x' || g, g, 'b' || g FROM generate_series(1, 8) g;
ALTER TABLE mx.t_tab_07 DROP COLUMN drop_a, DROP COLUMN drop_b;
ALTER TABLE mx.t_tab_07 ADD COLUMN added_after text;
UPDATE mx.t_tab_07 SET added_after = 'late-' || id WHERE id % 3 = 0;

-- TAB-08 and SEQ-07: both identity flavours, advanced past the seed.
CREATE TABLE mx.t_tab_08 (
  id_always  bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  id_default bigint GENERATED BY DEFAULT AS IDENTITY,
  label      text
);
INSERT INTO mx.t_tab_08 (label) SELECT 'identity-' || g FROM generate_series(1, 12) g;
INSERT INTO mx.t_tab_08 (id_default, label) VALUES (500, 'explicit-default');

-- TAB-10: an explicit collation next to the database default.
CREATE TABLE mx.t_tab_10 (
  id           integer,
  c_collate    text COLLATE "C",
  c_default    text
);
INSERT INTO mx.t_tab_10 SELECT g, 'C-' || g, 'default-' || g FROM generate_series(1, 6) g;

-- TAB-11: a column default calling nextval of a standalone sequence.
CREATE SEQUENCE mx.s_tab_11_seq;
CREATE TABLE mx.t_tab_11 (
  id   integer,
  code bigint DEFAULT nextval('mx.s_tab_11_seq')
);
INSERT INTO mx.t_tab_11 (id) SELECT g FROM generate_series(1, 9) g;

-- TAB-12: zero rows on purpose.
CREATE TABLE mx.t_tab_12 (id integer, payload text);

-- TAB-13: bulk.
CREATE TABLE mx.t_tab_13 (id integer, payload text);
INSERT INTO mx.t_tab_13 SELECT g, 'bulk-' || g FROM generate_series(1, 100000) g;

-- TAB-14: quoted mixed-case schema, table and reserved-word column.
CREATE TABLE "Mixed Schema"."Weird Table" (
  "Id"     integer,
  "select" text,
  "Order"  integer
);
INSERT INTO "Mixed Schema"."Weird Table"
SELECT g, 'reserved-' || g, g * 2 FROM generate_series(1, 4) g;

-- TAB-15: fifty columns.
CREATE TABLE mx.t_tab_15 AS
SELECT g AS id,
       'c01-' || g AS c01, 'c02-' || g AS c02, 'c03-' || g AS c03, 'c04-' || g AS c04,
       'c05-' || g AS c05, 'c06-' || g AS c06, 'c07-' || g AS c07, 'c08-' || g AS c08,
       'c09-' || g AS c09, 'c10-' || g AS c10, 'c11-' || g AS c11, 'c12-' || g AS c12,
       'c13-' || g AS c13, 'c14-' || g AS c14, 'c15-' || g AS c15, 'c16-' || g AS c16,
       'c17-' || g AS c17, 'c18-' || g AS c18, 'c19-' || g AS c19, 'c20-' || g AS c20,
       'c21-' || g AS c21, 'c22-' || g AS c22, 'c23-' || g AS c23, 'c24-' || g AS c24,
       'c25-' || g AS c25, 'c26-' || g AS c26, 'c27-' || g AS c27, 'c28-' || g AS c28,
       'c29-' || g AS c29, 'c30-' || g AS c30, 'c31-' || g AS c31, 'c32-' || g AS c32,
       'c33-' || g AS c33, 'c34-' || g AS c34, 'c35-' || g AS c35, 'c36-' || g AS c36,
       'c37-' || g AS c37, 'c38-' || g AS c38, 'c39-' || g AS c39, 'c40-' || g AS c40,
       'c41-' || g AS c41, 'c42-' || g AS c42, 'c43-' || g AS c43, 'c44-' || g AS c44,
       'c45-' || g AS c45, 'c46-' || g AS c46, 'c47-' || g AS c47, 'c48-' || g AS c48,
       'c49-' || g AS c49
FROM generate_series(1, 3) g;

-- TAB-16: TOAST-heavy, 1 MiB per value.
CREATE TABLE mx.t_tab_16 (id integer, blob text);
INSERT INTO mx.t_tab_16 SELECT g, repeat('x', 1048576) FROM generate_series(1, 200) g;

-- TAB-17: comments on the table and on a column.
CREATE TABLE mx.t_tab_17 (id integer, note text);
INSERT INTO mx.t_tab_17 SELECT g, 'commented-' || g FROM generate_series(1, 3) g;
COMMENT ON TABLE mx.t_tab_17 IS 'table comment for M-PG-TAB-17';
COMMENT ON COLUMN mx.t_tab_17.note IS 'column comment for M-PG-TAB-17';

-- TAB-18: owned by a non-superuser role, granted to two others.
CREATE TABLE mx.t_tab_18 (id integer, payload text);
INSERT INTO mx.t_tab_18 SELECT g, 'owned-' || g FROM generate_series(1, 5) g;
ALTER TABLE mx.t_tab_18 OWNER TO mx_owner;
GRANT SELECT ON mx.t_tab_18 TO mx_reader;
GRANT SELECT, INSERT, UPDATE, DELETE ON mx.t_tab_18 TO mx_writer;

-- Base relations for the index fixtures (M-PG-IDX-*).
CREATE TABLE mx.t_idx_base (
  id       integer,
  name     text,
  amount   numeric(10,2),
  flag     boolean,
  doc      jsonb,
  span     int4range,
  created  timestamptz
);
INSERT INTO mx.t_idx_base
SELECT g,
       'Name-' || g,
       (g * 3.5)::numeric(10,2),
       (g % 3 = 0),
       jsonb_build_object('k', g, 'list', jsonb_build_array(g, g + 1)),
       int4range(g, g + 10),
       TIMESTAMPTZ '2021-06-01 00:00:00+00' + (g || ' minutes')::interval
FROM generate_series(1, 300) g;

-- ---------------------------------------------------------------------------
-- Legacy coverage kept from the inline fixture (schema `app`, original names).
-- ---------------------------------------------------------------------------

CREATE TABLE app.accounts (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'active'
);
CREATE TABLE app.orders (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  acct bigint NOT NULL REFERENCES app.accounts (id),
  total numeric(12,2) NOT NULL
);
INSERT INTO app.accounts (email) SELECT 'u' || g || '@x' FROM generate_series(1, 500) g;
INSERT INTO app.orders (acct, total)
  SELECT (random() * 499)::int + 1, (random() * 1000)::numeric(12,2)
    FROM generate_series(1, 2000);

-- A dropped column in a long-lived table: `note` is the 4th live column but is
-- numbered 6 (regression of commit 1549128).
ALTER TABLE app.accounts ADD COLUMN legacy_a text, ADD COLUMN legacy_b int;
ALTER TABLE app.accounts DROP COLUMN legacy_a, DROP COLUMN legacy_b;
ALTER TABLE app.accounts ADD COLUMN note text;
UPDATE app.accounts SET note = 'n' || id WHERE id % 7 = 0;

-- Classic inheritance with rows in parent and child: a parent streamed without
-- ONLY would carry the child's rows twice.
CREATE TABLE app.log (id int, msg text);
CREATE TABLE app.log_2025 () INHERITS (app.log);
INSERT INTO app.log SELECT g, 'parent-' || g FROM generate_series(1, 10) g;
INSERT INTO app.log_2025 SELECT g, 'child-' || g FROM generate_series(1, 90) g;

-- A sequence owned by nobody, a function reading it, and a column default
-- calling that function: the default cannot be inlined unless functions are
-- created first.
CREATE SEQUENCE app.code_seq;
SELECT nextval('app.code_seq');
CREATE FUNCTION app.next_code() RETURNS text LANGUAGE sql
  AS $fn$ SELECT 'c' || nextval('app.code_seq') $fn$;
CREATE TABLE app.doc (id int, code text DEFAULT app.next_code());
INSERT INTO app.doc (id) SELECT g FROM generate_series(1, 5) g;

-- A function returning a table's row type: created AFTER that table, the
-- opposite dependency direction from the default above.
CREATE FUNCTION app.all_accounts() RETURNS SETOF app.accounts LANGUAGE sql
  AS $fn$ SELECT * FROM app.accounts $fn$;
