[package]
name = "rb-s3"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "rust-backup S3-compatible streaming module"

[dependencies]
rb-core = { path = "../rb-core" }
anyhow.workspace = true
async-trait.workspace = true
serde = { workspace = true }
serde_json.workspace = true
tokio = { workspace = true }
tracing.workspace = true
blake3.workspace = true
aws-config.workspace = true
aws-credential-types.workspace = true
aws-sdk-s3.workspace = true
aws-types.workspace = true
