[package]
name = "rb-postgres"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "rust-backup postgres module (PostgreSQL 10..=latest, logical, pure Rust)"

[dependencies]
rb-core = { path = "../rb-core" }
async-trait.workspace = true
blake3 = { workspace = true }
bytes = { workspace = true }
futures-util = { workspace = true }
serde = { workspace = true }
serde_json.workspace = true
tokio = { workspace = true }
tokio-postgres = { workspace = true }
tokio-postgres-rustls.workspace = true
tokio-rustls.workspace = true
webpki-roots.workspace = true
tracing.workspace = true
